Make actions fail if push to repository does not succeed

diff --git a/.github/workflows/update-task-tools.yml b/.github/workflows/update-task-tools.yml
--- a/.github/workflows/update-task-tools.yml
+++ b/.github/workflows/update-task-tools.yml
@@ -52,3 +52,5 @@ jobs:
             git pull --rebase origin main
             sleep 10
           done
+          echo "Could not push changes to repository!"
+          exit 1
